DROP TABLE IF EXISTS wish;

CREATE TABLE wish (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    title VARCHAR(100) NOT NULL COMMENT '愿望标题',
    description TEXT COMMENT '愿望描述',
    image_url VARCHAR(255) DEFAULT NULL COMMENT '图片URL',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-未完成，1-已完成',
    complete_time DATETIME DEFAULT NULL COMMENT '完成时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='愿望表'; 